### PR TITLE
add week 2 schedule

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**JIRA**
https://issues.jboss.org/browse/FH-4098

ping @JameelB for review
cc @damienomurchu @lgriffin @bofarrell @davidkirwan

### CODE REVIEW

**Review by davidkirwan — APPROVED** [review]
Looks fine to me. Just a quick question, have we communicated the fact we now want them here till 17:30 ?

**Comment by laurafitzgerald** [comment]
@davidkirwan That was the time sent in the original letters.

**Comment by damienomurchu** [comment]
same as @davidkirwan changes look good, but wasn't sure if their finish time was 100% nailed down

**Comment by laurafitzgerald** [comment]
ping @JameelB for review

**Review by JameelB — APPROVED** [review]

**Pull request merged**
