### PR TITLE
Use tutors ts

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**What**
Update to build scripts and instructions to use tutors-ts to build the site
Build and push related changes

**Why**
https://github.com/feedhenry/student-help-guide/issues/52

**Verification**
- run the build script.
- The build should occur with no changes as these are pushed
- The links from the left nav didn't work locally but they may work when the site is pushed so need to verify that afterwards. If they don't it's an issue with the package so can open an issue there.

@JameelB

### CODE REVIEW

**Review by JameelB — APPROVED** [review]
Looks good. Verified that the build script works as expected and that the built site renders as expected.

**Comment by laurafitzgerald** [comment]
Merging and will review the navigation links once published.

**Comment by damienomurchu** [comment]
Agree, best to merge. 

As seen, verifying that the site builds fine with the build.sh script, but the links from side navbar seem to be broken locally. 

Let's see if this is an issue also with the published site. If so, my initial suspicion is this is an issue the way the url's are constructed as the fully qualified url works `file:///home/damienmurphy/repos/student-help-guide/docs/topic02-schedule/index.html` but the navbar url doesn't `file:///topic02-schedule/book-schedule/index.html`

**Comment by laurafitzgerald** [comment]
@damienomurchu yes there is an issue with the published site also. 
I agree it's to do with how the links are generated. I imagine this needs to be resolved in the tutor-ts package. I will dig in and see if there's an easy fix there.

**Pull request merged**
